// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.Switch;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityDriverDashboardBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnAcceptRide;

  @NonNull
  public final LinearLayout cardRideRequest;

  @NonNull
  public final LinearLayout footer;

  @NonNull
  public final LinearLayout header;

  @NonNull
  public final MapView mapView;

  @NonNull
  public final Switch switchOnline;

  @NonNull
  public final TextView tvDriverName;

  @NonNull
  public final TextView tvDrop;

  @NonNull
  public final TextView tvEarnings;

  @NonNull
  public final TextView tvHistory;

  @NonNull
  public final TextView tvPickup;

  @NonNull
  public final TextView tvRideTitle;

  private ActivityDriverDashboardBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnAcceptRide, @NonNull LinearLayout cardRideRequest,
      @NonNull LinearLayout footer, @NonNull LinearLayout header, @NonNull MapView mapView,
      @NonNull Switch switchOnline, @NonNull TextView tvDriverName, @NonNull TextView tvDrop,
      @NonNull TextView tvEarnings, @NonNull TextView tvHistory, @NonNull TextView tvPickup,
      @NonNull TextView tvRideTitle) {
    this.rootView = rootView;
    this.btnAcceptRide = btnAcceptRide;
    this.cardRideRequest = cardRideRequest;
    this.footer = footer;
    this.header = header;
    this.mapView = mapView;
    this.switchOnline = switchOnline;
    this.tvDriverName = tvDriverName;
    this.tvDrop = tvDrop;
    this.tvEarnings = tvEarnings;
    this.tvHistory = tvHistory;
    this.tvPickup = tvPickup;
    this.tvRideTitle = tvRideTitle;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDriverDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDriverDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_driver_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDriverDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnAcceptRide;
      Button btnAcceptRide = ViewBindings.findChildViewById(rootView, id);
      if (btnAcceptRide == null) {
        break missingId;
      }

      id = R.id.cardRideRequest;
      LinearLayout cardRideRequest = ViewBindings.findChildViewById(rootView, id);
      if (cardRideRequest == null) {
        break missingId;
      }

      id = R.id.footer;
      LinearLayout footer = ViewBindings.findChildViewById(rootView, id);
      if (footer == null) {
        break missingId;
      }

      id = R.id.header;
      LinearLayout header = ViewBindings.findChildViewById(rootView, id);
      if (header == null) {
        break missingId;
      }

      id = R.id.mapView;
      MapView mapView = ViewBindings.findChildViewById(rootView, id);
      if (mapView == null) {
        break missingId;
      }

      id = R.id.switchOnline;
      Switch switchOnline = ViewBindings.findChildViewById(rootView, id);
      if (switchOnline == null) {
        break missingId;
      }

      id = R.id.tvDriverName;
      TextView tvDriverName = ViewBindings.findChildViewById(rootView, id);
      if (tvDriverName == null) {
        break missingId;
      }

      id = R.id.tvDrop;
      TextView tvDrop = ViewBindings.findChildViewById(rootView, id);
      if (tvDrop == null) {
        break missingId;
      }

      id = R.id.tvEarnings;
      TextView tvEarnings = ViewBindings.findChildViewById(rootView, id);
      if (tvEarnings == null) {
        break missingId;
      }

      id = R.id.tvHistory;
      TextView tvHistory = ViewBindings.findChildViewById(rootView, id);
      if (tvHistory == null) {
        break missingId;
      }

      id = R.id.tvPickup;
      TextView tvPickup = ViewBindings.findChildViewById(rootView, id);
      if (tvPickup == null) {
        break missingId;
      }

      id = R.id.tvRideTitle;
      TextView tvRideTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvRideTitle == null) {
        break missingId;
      }

      return new ActivityDriverDashboardBinding((ConstraintLayout) rootView, btnAcceptRide,
          cardRideRequest, footer, header, mapView, switchOnline, tvDriverName, tvDrop, tvEarnings,
          tvHistory, tvPickup, tvRideTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
