// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUserRegisterBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final Button btnUserRegister;

  @NonNull
  public final CheckBox chkRemember;

  @NonNull
  public final EditText etUserEmail;

  @NonNull
  public final EditText etUserName;

  @NonNull
  public final EditText etUserPassword;

  @NonNull
  public final EditText etUserPhone;

  @NonNull
  public final LinearLayout header;

  @NonNull
  public final ImageView imgLogo;

  private ActivityUserRegisterBinding(@NonNull NestedScrollView rootView,
      @NonNull Button btnUserRegister, @NonNull CheckBox chkRemember, @NonNull EditText etUserEmail,
      @NonNull EditText etUserName, @NonNull EditText etUserPassword, @NonNull EditText etUserPhone,
      @NonNull LinearLayout header, @NonNull ImageView imgLogo) {
    this.rootView = rootView;
    this.btnUserRegister = btnUserRegister;
    this.chkRemember = chkRemember;
    this.etUserEmail = etUserEmail;
    this.etUserName = etUserName;
    this.etUserPassword = etUserPassword;
    this.etUserPhone = etUserPhone;
    this.header = header;
    this.imgLogo = imgLogo;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnUserRegister;
      Button btnUserRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnUserRegister == null) {
        break missingId;
      }

      id = R.id.chkRemember;
      CheckBox chkRemember = ViewBindings.findChildViewById(rootView, id);
      if (chkRemember == null) {
        break missingId;
      }

      id = R.id.etUserEmail;
      EditText etUserEmail = ViewBindings.findChildViewById(rootView, id);
      if (etUserEmail == null) {
        break missingId;
      }

      id = R.id.etUserName;
      EditText etUserName = ViewBindings.findChildViewById(rootView, id);
      if (etUserName == null) {
        break missingId;
      }

      id = R.id.etUserPassword;
      EditText etUserPassword = ViewBindings.findChildViewById(rootView, id);
      if (etUserPassword == null) {
        break missingId;
      }

      id = R.id.etUserPhone;
      EditText etUserPhone = ViewBindings.findChildViewById(rootView, id);
      if (etUserPhone == null) {
        break missingId;
      }

      id = R.id.header;
      LinearLayout header = ViewBindings.findChildViewById(rootView, id);
      if (header == null) {
        break missingId;
      }

      id = R.id.imgLogo;
      ImageView imgLogo = ViewBindings.findChildViewById(rootView, id);
      if (imgLogo == null) {
        break missingId;
      }

      return new ActivityUserRegisterBinding((NestedScrollView) rootView, btnUserRegister,
          chkRemember, etUserEmail, etUserName, etUserPassword, etUserPhone, header, imgLogo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
