// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.ImageView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.coordinatorlayout.widget.CoordinatorLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import com.google.android.material.appbar.MaterialToolbar;
import com.google.android.material.bottomnavigation.BottomNavigationView;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityUserDashboardBinding implements ViewBinding {
  @NonNull
  private final CoordinatorLayout rootView;

  @NonNull
  public final BottomNavigationView bottomNav;

  @NonNull
  public final Button btnBookDriver;

  @NonNull
  public final Button btnQuickRide;

  @NonNull
  public final ImageView imgLogo;

  @NonNull
  public final MapView mapView;

  @NonNull
  public final MaterialToolbar topAppBar;

  private ActivityUserDashboardBinding(@NonNull CoordinatorLayout rootView,
      @NonNull BottomNavigationView bottomNav, @NonNull Button btnBookDriver,
      @NonNull Button btnQuickRide, @NonNull ImageView imgLogo, @NonNull MapView mapView,
      @NonNull MaterialToolbar topAppBar) {
    this.rootView = rootView;
    this.bottomNav = bottomNav;
    this.btnBookDriver = btnBookDriver;
    this.btnQuickRide = btnQuickRide;
    this.imgLogo = imgLogo;
    this.mapView = mapView;
    this.topAppBar = topAppBar;
  }

  @Override
  @NonNull
  public CoordinatorLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserDashboardBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_dashboard, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserDashboardBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.bottomNav;
      BottomNavigationView bottomNav = ViewBindings.findChildViewById(rootView, id);
      if (bottomNav == null) {
        break missingId;
      }

      id = R.id.btnBookDriver;
      Button btnBookDriver = ViewBindings.findChildViewById(rootView, id);
      if (btnBookDriver == null) {
        break missingId;
      }

      id = R.id.btnQuickRide;
      Button btnQuickRide = ViewBindings.findChildViewById(rootView, id);
      if (btnQuickRide == null) {
        break missingId;
      }

      id = R.id.imgLogo;
      ImageView imgLogo = ViewBindings.findChildViewById(rootView, id);
      if (imgLogo == null) {
        break missingId;
      }

      id = R.id.mapView;
      MapView mapView = ViewBindings.findChildViewById(rootView, id);
      if (mapView == null) {
        break missingId;
      }

      id = R.id.topAppBar;
      MaterialToolbar topAppBar = ViewBindings.findChildViewById(rootView, id);
      if (topAppBar == null) {
        break missingId;
      }

      return new ActivityUserDashboardBinding((CoordinatorLayout) rootView, bottomNav,
          btnBookDriver, btnQuickRide, imgLogo, mapView, topAppBar);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
