// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityDriverOngoingRideBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnArrived;

  @NonNull
  public final Button btnCompleteTrip;

  @NonNull
  public final Button btnOnTheWay;

  @NonNull
  public final Button btnStartTrip;

  @NonNull
  public final LinearLayout layoutButtons;

  @NonNull
  public final MapView mapViewOngoing;

  @NonNull
  public final TextView tvEta;

  @NonNull
  public final TextView tvRideInfo;

  private ActivityDriverOngoingRideBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnArrived, @NonNull Button btnCompleteTrip, @NonNull Button btnOnTheWay,
      @NonNull Button btnStartTrip, @NonNull LinearLayout layoutButtons,
      @NonNull MapView mapViewOngoing, @NonNull TextView tvEta, @NonNull TextView tvRideInfo) {
    this.rootView = rootView;
    this.btnArrived = btnArrived;
    this.btnCompleteTrip = btnCompleteTrip;
    this.btnOnTheWay = btnOnTheWay;
    this.btnStartTrip = btnStartTrip;
    this.layoutButtons = layoutButtons;
    this.mapViewOngoing = mapViewOngoing;
    this.tvEta = tvEta;
    this.tvRideInfo = tvRideInfo;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDriverOngoingRideBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDriverOngoingRideBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_driver_ongoing_ride, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDriverOngoingRideBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnArrived;
      Button btnArrived = ViewBindings.findChildViewById(rootView, id);
      if (btnArrived == null) {
        break missingId;
      }

      id = R.id.btnCompleteTrip;
      Button btnCompleteTrip = ViewBindings.findChildViewById(rootView, id);
      if (btnCompleteTrip == null) {
        break missingId;
      }

      id = R.id.btnOnTheWay;
      Button btnOnTheWay = ViewBindings.findChildViewById(rootView, id);
      if (btnOnTheWay == null) {
        break missingId;
      }

      id = R.id.btnStartTrip;
      Button btnStartTrip = ViewBindings.findChildViewById(rootView, id);
      if (btnStartTrip == null) {
        break missingId;
      }

      id = R.id.layoutButtons;
      LinearLayout layoutButtons = ViewBindings.findChildViewById(rootView, id);
      if (layoutButtons == null) {
        break missingId;
      }

      id = R.id.mapViewOngoing;
      MapView mapViewOngoing = ViewBindings.findChildViewById(rootView, id);
      if (mapViewOngoing == null) {
        break missingId;
      }

      id = R.id.tvEta;
      TextView tvEta = ViewBindings.findChildViewById(rootView, id);
      if (tvEta == null) {
        break missingId;
      }

      id = R.id.tvRideInfo;
      TextView tvRideInfo = ViewBindings.findChildViewById(rootView, id);
      if (tvRideInfo == null) {
        break missingId;
      }

      return new ActivityDriverOngoingRideBinding((ConstraintLayout) rootView, btnArrived,
          btnCompleteTrip, btnOnTheWay, btnStartTrip, layoutButtons, mapViewOngoing, tvEta,
          tvRideInfo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
