// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.core.widget.NestedScrollView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityDriverRegisterBinding implements ViewBinding {
  @NonNull
  private final NestedScrollView rootView;

  @NonNull
  public final Button btnDriverRegister;

  @NonNull
  public final CheckBox chkRemember;

  @NonNull
  public final EditText etDriverEmail;

  @NonNull
  public final EditText etDriverName;

  @NonNull
  public final EditText etDriverPassword;

  @NonNull
  public final EditText etDriverPhone;

  @NonNull
  public final EditText etLicenseNumber;

  @NonNull
  public final EditText etVehicleNumber;

  @NonNull
  public final EditText etVehicleType;

  @NonNull
  public final LinearLayout header;

  @NonNull
  public final ImageView imgLogo;

  private ActivityDriverRegisterBinding(@NonNull NestedScrollView rootView,
      @NonNull Button btnDriverRegister, @NonNull CheckBox chkRemember,
      @NonNull EditText etDriverEmail, @NonNull EditText etDriverName,
      @NonNull EditText etDriverPassword, @NonNull EditText etDriverPhone,
      @NonNull EditText etLicenseNumber, @NonNull EditText etVehicleNumber,
      @NonNull EditText etVehicleType, @NonNull LinearLayout header, @NonNull ImageView imgLogo) {
    this.rootView = rootView;
    this.btnDriverRegister = btnDriverRegister;
    this.chkRemember = chkRemember;
    this.etDriverEmail = etDriverEmail;
    this.etDriverName = etDriverName;
    this.etDriverPassword = etDriverPassword;
    this.etDriverPhone = etDriverPhone;
    this.etLicenseNumber = etLicenseNumber;
    this.etVehicleNumber = etVehicleNumber;
    this.etVehicleType = etVehicleType;
    this.header = header;
    this.imgLogo = imgLogo;
  }

  @Override
  @NonNull
  public NestedScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityDriverRegisterBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityDriverRegisterBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_driver_register, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityDriverRegisterBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnDriverRegister;
      Button btnDriverRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnDriverRegister == null) {
        break missingId;
      }

      id = R.id.chkRemember;
      CheckBox chkRemember = ViewBindings.findChildViewById(rootView, id);
      if (chkRemember == null) {
        break missingId;
      }

      id = R.id.etDriverEmail;
      EditText etDriverEmail = ViewBindings.findChildViewById(rootView, id);
      if (etDriverEmail == null) {
        break missingId;
      }

      id = R.id.etDriverName;
      EditText etDriverName = ViewBindings.findChildViewById(rootView, id);
      if (etDriverName == null) {
        break missingId;
      }

      id = R.id.etDriverPassword;
      EditText etDriverPassword = ViewBindings.findChildViewById(rootView, id);
      if (etDriverPassword == null) {
        break missingId;
      }

      id = R.id.etDriverPhone;
      EditText etDriverPhone = ViewBindings.findChildViewById(rootView, id);
      if (etDriverPhone == null) {
        break missingId;
      }

      id = R.id.etLicenseNumber;
      EditText etLicenseNumber = ViewBindings.findChildViewById(rootView, id);
      if (etLicenseNumber == null) {
        break missingId;
      }

      id = R.id.etVehicleNumber;
      EditText etVehicleNumber = ViewBindings.findChildViewById(rootView, id);
      if (etVehicleNumber == null) {
        break missingId;
      }

      id = R.id.etVehicleType;
      EditText etVehicleType = ViewBindings.findChildViewById(rootView, id);
      if (etVehicleType == null) {
        break missingId;
      }

      id = R.id.header;
      LinearLayout header = ViewBindings.findChildViewById(rootView, id);
      if (header == null) {
        break missingId;
      }

      id = R.id.imgLogo;
      ImageView imgLogo = ViewBindings.findChildViewById(rootView, id);
      if (imgLogo == null) {
        break missingId;
      }

      return new ActivityDriverRegisterBinding((NestedScrollView) rootView, btnDriverRegister,
          chkRemember, etDriverEmail, etDriverName, etDriverPassword, etDriverPhone,
          etLicenseNumber, etVehicleNumber, etVehicleType, header, imgLogo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
