// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.CheckBox;
import android.widget.EditText;
import android.widget.ImageView;
import android.widget.LinearLayout;
import android.widget.RadioButton;
import android.widget.RadioGroup;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityLoginBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnLogin;

  @NonNull
  public final CheckBox chkRemember;

  @NonNull
  public final EditText etEmail;

  @NonNull
  public final EditText etPassword;

  @NonNull
  public final ImageView imgLogo;

  @NonNull
  public final RadioButton rbDriver;

  @NonNull
  public final RadioButton rbUser;

  @NonNull
  public final RadioGroup roleGroup;

  @NonNull
  public final TextView tvTitle;

  private ActivityLoginBinding(@NonNull LinearLayout rootView, @NonNull Button btnLogin,
      @NonNull CheckBox chkRemember, @NonNull EditText etEmail, @NonNull EditText etPassword,
      @NonNull ImageView imgLogo, @NonNull RadioButton rbDriver, @NonNull RadioButton rbUser,
      @NonNull RadioGroup roleGroup, @NonNull TextView tvTitle) {
    this.rootView = rootView;
    this.btnLogin = btnLogin;
    this.chkRemember = chkRemember;
    this.etEmail = etEmail;
    this.etPassword = etPassword;
    this.imgLogo = imgLogo;
    this.rbDriver = rbDriver;
    this.rbUser = rbUser;
    this.roleGroup = roleGroup;
    this.tvTitle = tvTitle;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityLoginBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_login, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityLoginBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnLogin;
      Button btnLogin = ViewBindings.findChildViewById(rootView, id);
      if (btnLogin == null) {
        break missingId;
      }

      id = R.id.chkRemember;
      CheckBox chkRemember = ViewBindings.findChildViewById(rootView, id);
      if (chkRemember == null) {
        break missingId;
      }

      id = R.id.etEmail;
      EditText etEmail = ViewBindings.findChildViewById(rootView, id);
      if (etEmail == null) {
        break missingId;
      }

      id = R.id.etPassword;
      EditText etPassword = ViewBindings.findChildViewById(rootView, id);
      if (etPassword == null) {
        break missingId;
      }

      id = R.id.imgLogo;
      ImageView imgLogo = ViewBindings.findChildViewById(rootView, id);
      if (imgLogo == null) {
        break missingId;
      }

      id = R.id.rbDriver;
      RadioButton rbDriver = ViewBindings.findChildViewById(rootView, id);
      if (rbDriver == null) {
        break missingId;
      }

      id = R.id.rbUser;
      RadioButton rbUser = ViewBindings.findChildViewById(rootView, id);
      if (rbUser == null) {
        break missingId;
      }

      id = R.id.roleGroup;
      RadioGroup roleGroup = ViewBindings.findChildViewById(rootView, id);
      if (roleGroup == null) {
        break missingId;
      }

      id = R.id.tvTitle;
      TextView tvTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvTitle == null) {
        break missingId;
      }

      return new ActivityLoginBinding((LinearLayout) rootView, btnLogin, chkRemember, etEmail,
          etPassword, imgLogo, rbDriver, rbUser, roleGroup, tvTitle);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
