// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.LinearLayout;
import android.widget.RatingBar;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityUserRideCompleteBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnMarkCash;

  @NonNull
  public final Button btnPayNow;

  @NonNull
  public final Button btnSubmitRating;

  @NonNull
  public final EditText etRatingComment;

  @NonNull
  public final LinearLayout layoutPayments;

  @NonNull
  public final RatingBar ratingBar;

  @NonNull
  public final TextView tvCompleteTitle;

  @NonNull
  public final TextView tvDriverNameFinal;

  @NonNull
  public final TextView tvFinalFare;

  @NonNull
  public final TextView tvRateLabel;

  private ActivityUserRideCompleteBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnMarkCash, @NonNull Button btnPayNow, @NonNull Button btnSubmitRating,
      @NonNull EditText etRatingComment, @NonNull LinearLayout layoutPayments,
      @NonNull RatingBar ratingBar, @NonNull TextView tvCompleteTitle,
      @NonNull TextView tvDriverNameFinal, @NonNull TextView tvFinalFare,
      @NonNull TextView tvRateLabel) {
    this.rootView = rootView;
    this.btnMarkCash = btnMarkCash;
    this.btnPayNow = btnPayNow;
    this.btnSubmitRating = btnSubmitRating;
    this.etRatingComment = etRatingComment;
    this.layoutPayments = layoutPayments;
    this.ratingBar = ratingBar;
    this.tvCompleteTitle = tvCompleteTitle;
    this.tvDriverNameFinal = tvDriverNameFinal;
    this.tvFinalFare = tvFinalFare;
    this.tvRateLabel = tvRateLabel;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserRideCompleteBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserRideCompleteBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_ride_complete, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserRideCompleteBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnMarkCash;
      Button btnMarkCash = ViewBindings.findChildViewById(rootView, id);
      if (btnMarkCash == null) {
        break missingId;
      }

      id = R.id.btnPayNow;
      Button btnPayNow = ViewBindings.findChildViewById(rootView, id);
      if (btnPayNow == null) {
        break missingId;
      }

      id = R.id.btnSubmitRating;
      Button btnSubmitRating = ViewBindings.findChildViewById(rootView, id);
      if (btnSubmitRating == null) {
        break missingId;
      }

      id = R.id.etRatingComment;
      EditText etRatingComment = ViewBindings.findChildViewById(rootView, id);
      if (etRatingComment == null) {
        break missingId;
      }

      id = R.id.layoutPayments;
      LinearLayout layoutPayments = ViewBindings.findChildViewById(rootView, id);
      if (layoutPayments == null) {
        break missingId;
      }

      id = R.id.ratingBar;
      RatingBar ratingBar = ViewBindings.findChildViewById(rootView, id);
      if (ratingBar == null) {
        break missingId;
      }

      id = R.id.tvCompleteTitle;
      TextView tvCompleteTitle = ViewBindings.findChildViewById(rootView, id);
      if (tvCompleteTitle == null) {
        break missingId;
      }

      id = R.id.tvDriverNameFinal;
      TextView tvDriverNameFinal = ViewBindings.findChildViewById(rootView, id);
      if (tvDriverNameFinal == null) {
        break missingId;
      }

      id = R.id.tvFinalFare;
      TextView tvFinalFare = ViewBindings.findChildViewById(rootView, id);
      if (tvFinalFare == null) {
        break missingId;
      }

      id = R.id.tvRateLabel;
      TextView tvRateLabel = ViewBindings.findChildViewById(rootView, id);
      if (tvRateLabel == null) {
        break missingId;
      }

      return new ActivityUserRideCompleteBinding((ConstraintLayout) rootView, btnMarkCash,
          btnPayNow, btnSubmitRating, etRatingComment, layoutPayments, ratingBar, tvCompleteTitle,
          tvDriverNameFinal, tvFinalFare, tvRateLabel);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
