// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityUserRideTrackingBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final LinearLayout layoutBottom;

  @NonNull
  public final MapView mapViewUserRide;

  @NonNull
  public final TextView tvDriverInfo;

  @NonNull
  public final TextView tvEtaUser;

  @NonNull
  public final TextView tvFromTo;

  @NonNull
  public final TextView tvRideStatus;

  private ActivityUserRideTrackingBinding(@NonNull ConstraintLayout rootView,
      @NonNull LinearLayout layoutBottom, @NonNull MapView mapViewUserRide,
      @NonNull TextView tvDriverInfo, @NonNull TextView tvEtaUser, @NonNull TextView tvFromTo,
      @NonNull TextView tvRideStatus) {
    this.rootView = rootView;
    this.layoutBottom = layoutBottom;
    this.mapViewUserRide = mapViewUserRide;
    this.tvDriverInfo = tvDriverInfo;
    this.tvEtaUser = tvEtaUser;
    this.tvFromTo = tvFromTo;
    this.tvRideStatus = tvRideStatus;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityUserRideTrackingBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityUserRideTrackingBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_user_ride_tracking, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityUserRideTrackingBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.layoutBottom;
      LinearLayout layoutBottom = ViewBindings.findChildViewById(rootView, id);
      if (layoutBottom == null) {
        break missingId;
      }

      id = R.id.mapViewUserRide;
      MapView mapViewUserRide = ViewBindings.findChildViewById(rootView, id);
      if (mapViewUserRide == null) {
        break missingId;
      }

      id = R.id.tvDriverInfo;
      TextView tvDriverInfo = ViewBindings.findChildViewById(rootView, id);
      if (tvDriverInfo == null) {
        break missingId;
      }

      id = R.id.tvEtaUser;
      TextView tvEtaUser = ViewBindings.findChildViewById(rootView, id);
      if (tvEtaUser == null) {
        break missingId;
      }

      id = R.id.tvFromTo;
      TextView tvFromTo = ViewBindings.findChildViewById(rootView, id);
      if (tvFromTo == null) {
        break missingId;
      }

      id = R.id.tvRideStatus;
      TextView tvRideStatus = ViewBindings.findChildViewById(rootView, id);
      if (tvRideStatus == null) {
        break missingId;
      }

      return new ActivityUserRideTrackingBinding((ConstraintLayout) rootView, layoutBottom,
          mapViewUserRide, tvDriverInfo, tvEtaUser, tvFromTo, tvRideStatus);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
