// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.EditText;
import android.widget.ScrollView;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRoundTripBinding implements ViewBinding {
  @NonNull
  private final ScrollView rootView;

  @NonNull
  public final Button btnConfirm;

  @NonNull
  public final Button btnEstimate;

  @NonNull
  public final EditText etFinalDestination;

  @NonNull
  public final EditText etFrom;

  @NonNull
  public final EditText etTo;

  @NonNull
  public final TextView tvEndDateTime;

  @NonNull
  public final TextView tvPricing;

  @NonNull
  public final TextView tvStartDateTime;

  @NonNull
  public final TextView tvTotal;

  private ActivityRoundTripBinding(@NonNull ScrollView rootView, @NonNull Button btnConfirm,
      @NonNull Button btnEstimate, @NonNull EditText etFinalDestination, @NonNull EditText etFrom,
      @NonNull EditText etTo, @NonNull TextView tvEndDateTime, @NonNull TextView tvPricing,
      @NonNull TextView tvStartDateTime, @NonNull TextView tvTotal) {
    this.rootView = rootView;
    this.btnConfirm = btnConfirm;
    this.btnEstimate = btnEstimate;
    this.etFinalDestination = etFinalDestination;
    this.etFrom = etFrom;
    this.etTo = etTo;
    this.tvEndDateTime = tvEndDateTime;
    this.tvPricing = tvPricing;
    this.tvStartDateTime = tvStartDateTime;
    this.tvTotal = tvTotal;
  }

  @Override
  @NonNull
  public ScrollView getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRoundTripBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRoundTripBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_round_trip, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRoundTripBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnConfirm;
      Button btnConfirm = ViewBindings.findChildViewById(rootView, id);
      if (btnConfirm == null) {
        break missingId;
      }

      id = R.id.btnEstimate;
      Button btnEstimate = ViewBindings.findChildViewById(rootView, id);
      if (btnEstimate == null) {
        break missingId;
      }

      id = R.id.etFinalDestination;
      EditText etFinalDestination = ViewBindings.findChildViewById(rootView, id);
      if (etFinalDestination == null) {
        break missingId;
      }

      id = R.id.etFrom;
      EditText etFrom = ViewBindings.findChildViewById(rootView, id);
      if (etFrom == null) {
        break missingId;
      }

      id = R.id.etTo;
      EditText etTo = ViewBindings.findChildViewById(rootView, id);
      if (etTo == null) {
        break missingId;
      }

      id = R.id.tvEndDateTime;
      TextView tvEndDateTime = ViewBindings.findChildViewById(rootView, id);
      if (tvEndDateTime == null) {
        break missingId;
      }

      id = R.id.tvPricing;
      TextView tvPricing = ViewBindings.findChildViewById(rootView, id);
      if (tvPricing == null) {
        break missingId;
      }

      id = R.id.tvStartDateTime;
      TextView tvStartDateTime = ViewBindings.findChildViewById(rootView, id);
      if (tvStartDateTime == null) {
        break missingId;
      }

      id = R.id.tvTotal;
      TextView tvTotal = ViewBindings.findChildViewById(rootView, id);
      if (tvTotal == null) {
        break missingId;
      }

      return new ActivityRoundTripBinding((ScrollView) rootView, btnConfirm, btnEstimate,
          etFinalDestination, etFrom, etTo, tvEndDateTime, tvPricing, tvStartDateTime, tvTotal);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
