// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.AutoCompleteTextView;
import android.widget.Button;
import android.widget.EditText;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.constraintlayout.widget.ConstraintLayout;
import androidx.recyclerview.widget.RecyclerView;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import com.google.android.material.appbar.MaterialToolbar;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;
import org.osmdroid.views.MapView;

public final class ActivityBookRideBinding implements ViewBinding {
  @NonNull
  private final ConstraintLayout rootView;

  @NonNull
  public final Button btnConfirmRide;

  @NonNull
  public final Button btnEstimateFare;

  @NonNull
  public final EditText etFrom;

  @NonNull
  public final AutoCompleteTextView etTo;

  @NonNull
  public final MapView mapViewRide;

  @NonNull
  public final RecyclerView rvVehicleOptions;

  @NonNull
  public final MaterialToolbar topBar;

  @NonNull
  public final TextView tvDistance;

  @NonNull
  public final TextView tvInfo;

  private ActivityBookRideBinding(@NonNull ConstraintLayout rootView,
      @NonNull Button btnConfirmRide, @NonNull Button btnEstimateFare, @NonNull EditText etFrom,
      @NonNull AutoCompleteTextView etTo, @NonNull MapView mapViewRide,
      @NonNull RecyclerView rvVehicleOptions, @NonNull MaterialToolbar topBar,
      @NonNull TextView tvDistance, @NonNull TextView tvInfo) {
    this.rootView = rootView;
    this.btnConfirmRide = btnConfirmRide;
    this.btnEstimateFare = btnEstimateFare;
    this.etFrom = etFrom;
    this.etTo = etTo;
    this.mapViewRide = mapViewRide;
    this.rvVehicleOptions = rvVehicleOptions;
    this.topBar = topBar;
    this.tvDistance = tvDistance;
    this.tvInfo = tvInfo;
  }

  @Override
  @NonNull
  public ConstraintLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityBookRideBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityBookRideBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_book_ride, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityBookRideBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnConfirmRide;
      Button btnConfirmRide = ViewBindings.findChildViewById(rootView, id);
      if (btnConfirmRide == null) {
        break missingId;
      }

      id = R.id.btnEstimateFare;
      Button btnEstimateFare = ViewBindings.findChildViewById(rootView, id);
      if (btnEstimateFare == null) {
        break missingId;
      }

      id = R.id.etFrom;
      EditText etFrom = ViewBindings.findChildViewById(rootView, id);
      if (etFrom == null) {
        break missingId;
      }

      id = R.id.etTo;
      AutoCompleteTextView etTo = ViewBindings.findChildViewById(rootView, id);
      if (etTo == null) {
        break missingId;
      }

      id = R.id.mapViewRide;
      MapView mapViewRide = ViewBindings.findChildViewById(rootView, id);
      if (mapViewRide == null) {
        break missingId;
      }

      id = R.id.rvVehicleOptions;
      RecyclerView rvVehicleOptions = ViewBindings.findChildViewById(rootView, id);
      if (rvVehicleOptions == null) {
        break missingId;
      }

      id = R.id.topBar;
      MaterialToolbar topBar = ViewBindings.findChildViewById(rootView, id);
      if (topBar == null) {
        break missingId;
      }

      id = R.id.tvDistance;
      TextView tvDistance = ViewBindings.findChildViewById(rootView, id);
      if (tvDistance == null) {
        break missingId;
      }

      id = R.id.tvInfo;
      TextView tvInfo = ViewBindings.findChildViewById(rootView, id);
      if (tvInfo == null) {
        break missingId;
      }

      return new ActivityBookRideBinding((ConstraintLayout) rootView, btnConfirmRide,
          btnEstimateFare, etFrom, etTo, mapViewRide, rvVehicleOptions, topBar, tvDistance, tvInfo);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
