// Generated by view binder compiler. Do not edit!
package com.example.letsgo.databinding;

import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.Button;
import android.widget.LinearLayout;
import android.widget.TextView;
import androidx.annotation.NonNull;
import androidx.annotation.Nullable;
import androidx.viewbinding.ViewBinding;
import androidx.viewbinding.ViewBindings;
import com.example.letsgo.R;
import java.lang.NullPointerException;
import java.lang.Override;
import java.lang.String;

public final class ActivityRegisterChoiceBinding implements ViewBinding {
  @NonNull
  private final LinearLayout rootView;

  @NonNull
  public final Button btnDriverRegister;

  @NonNull
  public final Button btnUserRegister;

  @NonNull
  public final TextView tvRegisterAs;

  private ActivityRegisterChoiceBinding(@NonNull LinearLayout rootView,
      @NonNull Button btnDriverRegister, @NonNull Button btnUserRegister,
      @NonNull TextView tvRegisterAs) {
    this.rootView = rootView;
    this.btnDriverRegister = btnDriverRegister;
    this.btnUserRegister = btnUserRegister;
    this.tvRegisterAs = tvRegisterAs;
  }

  @Override
  @NonNull
  public LinearLayout getRoot() {
    return rootView;
  }

  @NonNull
  public static ActivityRegisterChoiceBinding inflate(@NonNull LayoutInflater inflater) {
    return inflate(inflater, null, false);
  }

  @NonNull
  public static ActivityRegisterChoiceBinding inflate(@NonNull LayoutInflater inflater,
      @Nullable ViewGroup parent, boolean attachToParent) {
    View root = inflater.inflate(R.layout.activity_register_choice, parent, false);
    if (attachToParent) {
      parent.addView(root);
    }
    return bind(root);
  }

  @NonNull
  public static ActivityRegisterChoiceBinding bind(@NonNull View rootView) {
    // The body of this method is generated in a way you would not otherwise write.
    // This is done to optimize the compiled bytecode for size and performance.
    int id;
    missingId: {
      id = R.id.btnDriverRegister;
      Button btnDriverRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnDriverRegister == null) {
        break missingId;
      }

      id = R.id.btnUserRegister;
      Button btnUserRegister = ViewBindings.findChildViewById(rootView, id);
      if (btnUserRegister == null) {
        break missingId;
      }

      id = R.id.tvRegisterAs;
      TextView tvRegisterAs = ViewBindings.findChildViewById(rootView, id);
      if (tvRegisterAs == null) {
        break missingId;
      }

      return new ActivityRegisterChoiceBinding((LinearLayout) rootView, btnDriverRegister,
          btnUserRegister, tvRegisterAs);
    }
    String missingId = rootView.getResources().getResourceName(id);
    throw new NullPointerException("Missing required view with ID: ".concat(missingId));
  }
}
